### ISSUE TITLE
Using the plugin visually?

### ISSUE THREAD

**Issue by Alorse** [devgeniem/wp-sanitize-accented-uploads#4]
I want to use visually plugin from the wp-admin wordpress, how do I do?
PS: No I have access to WP-CLI

**Comment by onnimonni** [comment]
Hey Alorse!

Sorry you can't and I have currently no plans for creating any. I recommend on switching to service provider which allows you to use `$ wp` from commandline. If you'll want to make a gui for this plugin it should be relatively easy by just forking it and using the functions from `wp-cli-integration.php`.
